version: "1.0"
services:
  database:
    build: .
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/A_init.sql
      - ./data:/var/lib/postgresql/data