name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
        working-directory: rag-toolchain

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --lib --lcov --output-path lcov.info
        working-directory: rag-toolchain

      - name: Install grcov
        run: cargo install grcov

      - name: Generate coverage report
        run: grcov rag-toolchain/lcov.info -t html --ignore-not-existing -o coverage_report.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report.html
          path: coverage_report.html 