name: Integration tests 

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      working-directory: rag-toolchain/tests/pg_vector_integration_test/docker 

    - name: Run integration test
      run: cargo test --test mod -- --nocapture
      working-directory: rag-toolchain/tests/pg_vector_integration_test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
      working-directory: rag-toolchain/tests/pg_vector_integration_test/docker 