name: Rust Build / Unit Test / Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build project
        run: cargo build

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --lib --lcov --output-path unitlcov.info

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --test mod --lcov --output-path integrationlcov.info

  lint:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run linter
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

  doc-test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run doc tests
        run: cargo test --doc

  coverage:
    needs:
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: rag-toolchain
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: unitlcov.info,integrationlcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
